spawndir: .spawndir

components:
  - entrypoint: [ npm ]
    cmd: [ start ]
    workdir: reveal.js.tmp
    tee:
      combined: true
    before:
      - entrypoint: [ npm, i ]
        workdir: reveal.js.tmp
        tee:
          combined: true
        before:
          - entrypoint: [ ln ]
            cmd: [ -s, -f, "{{.ContextDir}}/index.html", reveal.js.tmp/index.html ]
            tee:
              combined: true
            before:
              - entrypoint: [ git ]
                cmd: [ clone, https://github.com/hakimel/reveal.js.git, reveal.js.tmp ]
  - entrypoint: [ ttyd, -c, user:passw0rd, -p, 2375, -m, 1 ]
    cmd: [ zsh ]
    workdir: "{{.ContextDir}}"
    skip-prefix: true
    tee:
      combined: true
